### ISSUE TITLE
how to run on Windows

### ISSUE THREAD

**Issue by lucamaf** [3scale-labs/3scale_toolbox_packaging#23]
I see an executable folder in the source code release package after unzipping it.
this contains a '3scale' file. Tried to rename to '3scale.exe' but WIN10 complains the executable is not compatible, when trying to run it.

**Comment by eguzki** [comment]
no need to rename to 3scale.exe. `3scale` file in `bin` directory is a script file run by `ruby.exe` bundled with the installation.

I just tested latest release ([v0.16.0](https://github.com/3scale/3scale_toolbox_packaging/releases/download/v0.16.1/3scale-toolbox-0.16.0-1-x64.msi)) and it is working with Windows 10. Just open terminal and type:

`3scale -v`

It should run correctly.
