### ISSUE TITLE
Mac OSX version not available with v0.18

### ISSUE THREAD

**Issue by hguerrero** [3scale-labs/3scale_toolbox_packaging#36]
There is no *.pkg file generated for version 0.18.0

**Comment by eguzki** [comment]
It is unexpectedly failing. After some analysis, it seems to be a travis issue, they changed the base image used to build OSX and now some dep is not found. I will investigate further. 

I ran an old OSX build that worked (for 0.16.0) and now it is failing with exactly the same codebase and travis conf. Very weird. I am waiting for the new travis-ci.com app and check if it works.

**Comment by eguzki** [comment]
The Mac OS pkg building has been discontinued. Instead, RVM framework is leveraged to install 3scale_toolbox gem. Doc has been updated:

```

    Install RVM

curl -sSL https://get.rvm.io | bash -s stable

    Install Ruby 2.7.1

rvm install 2.7.1

    Use Ruby 2.7.1

rvm use 2.7.1

    Install 3scale_toolbox gem

gem install 3scale_toolbox

    Test executing help command

3scale help
```

Reopen the issue for further discussion.
